# Configuration for the repo
REPO:
  NAME: cah_bot
  URL: https://github.com/barretobrock/${REPO_NAME}
  GIT_URL: git+${REPO_URL}.git#egg=${REPO_NAME}
  DIR: ${HOME}/extras/${REPO_NAME}
  VENV: ${HOME}/venvs/cah_bot/bin/python
  DESC: A slack bot for homeautomation & other things
  DEPS:
    - git+https://github.com/barretobrock/slacktools.git#egg=slacktools
